FROM ubuntu:latest

# Prevents interaction during install
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    apt-utils \
    iptables \
    iproute2 \
    tcpdump \
    traceroute \
    iputils-ping \
    net-tools \
    && apt clean && rm -rf /var/lib/apt/lists/*
